# Total Cases {#total_cases}

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	eval=FALSE,
	message = FALSE,
	warning = FALSE
)
source("../scripts/source_files.R")
```

```{sql connection=con, include=FALSE, output.var='db_tables'}
SELECT table_name FROM information_schema.tables
                 WHERE table_schema='public'
```

# Master file of cases for all three states
```{sql connection=con, output.var='master_case_file'}
select * from case_details where case_flag = '1'
```


## Year on Year
```{sql connection=con, output.var='year_wise_cases'}
select state_name, district_name, fil_year, reg_year_date, count(cino) as total_cases, 
sum(case when disp_nature = '0' then 1 else 0 end) as pending_cases,
sum(case when disp_nature != '0' then 1 else 0 end) as disposed_cases
from case_details where case_flag = '1' group by state_name, district_name, fil_year, reg_year_date
```

There are cases with filing year as 0 in Assam and Haryana. Generating a set of all such cases for a deep dive

```{sql connection=con, output.var='filing_year_0'}
select state_name, district_name, est_code, court_name, cino, fil_no,date_of_filing, reg_no, reg_year_date, updated_type_name, disp_nature, updated_disp_name from case_details where fil_year = '0' and case_flag = '1'
```

For some cases, the filing year is less than 2012. What are these cases ?
```{sql connection=con, output.var='filing_year_below_2012'}
select state_name, district_name, est_code, court_name, cino, fil_no,date_of_filing, reg_no, reg_year_date, updated_type_name, disp_nature, updated_disp_name from case_details where fil_year IN ('2004','2008','2009','2010') AND case_flag = '1'
```

## Year wise FIR
```{sql connection=con, output.var='year_wise_FIR'}
select state_name, district_name, fir_year, fil_year, reg_year_date, count(cino) as total_cases from case_details where case_flag = '1' group by state_name, district_name,fir_year, fil_year, reg_year_date
```

## Disposal Nature
```{sql connection=con, output.var='nature_of_disposal'}
select state_name, district_name, updated_disp_name, disp_nature, fil_year, reg_year_date, EXTRACT(year from date_of_decision) as decision_year, count(cino) as total_cases from case_details where disp_nature != '0' AND case_flag = '1' group by state_name, district_name, updated_disp_name, disp_nature, fil_year, reg_year_date, decision_year
```

## Offence wise
```{sql connection=con, output.var='nature_of_offence'}
select state_name, district_name, est_code, court_name, reg_year, fil_year, decision_year, act_name_std, section_name_std, count(cino) as total_cases from (select c.act_name_std, c.section_name_std, d.* from acts_subset as c inner join (select a.*, b.state_name, b.district_name, b.est_code, b.court_name, b.reg_year, b.fil_year, EXTRACT(year from date_of_decision) as decision_year FROM case_acts as a LEFT JOIN case_details as b on a.cino=b.cino) as d on c.id = d.act) as e group by state_name, district_name, est_code, court_name, reg_year, fil_year, decision_year, act_name_std, section_name_std
```

## Age of case
```{sql connection=con, output.var='case_age_raw'}
select state_name, district_name, court_name, est_code, cino,reg_year_date, fil_year, updated_type_name, updated_disp_name, disp_nature, dt_regis, date_of_filing, date_of_decision from case_details where case_flag = '1'
```


```{r processing-case-age}
case_age <- case_age_raw
case_age$end_date <- case_age$date_of_decision 

# End date of a case should depend on when the data was downloaded for a state. This will ensure that we capture the correct status of a case (pending/disposed) as on the date of data-collection. 

# At present, we're using a fix date - 2020/03/31, but this will be updated as per the revised date of data collection for each state

case_age$end_date[is.na(case_age$end_date)] <- as.Date("2020-03-31")
case_age$decision_year <- year(case_age$end_date)
case_age$decision_year[case_age$disp_nature == 0] <- NA_character_

# Case age is calculated as a difference between the date of decision (disposed cases) or 2020/03/31 (pending cases) and the date of registration (dt_regis) of a case

case_age$age_of_case_interval <- lubridate::interval(case_age$dt_regis,case_age$end_date)

case_age$age_of_case_days <- time_length(case_age$age_of_case_interval, "days")

# Remove cases with difference < 0
cases_removed <- case_age[case_age$age_of_case_days < 0,]
write_csv(cases_removed,"datasets/case_age_negative.csv")

case_age <- case_age[case_age$age_of_case_days >= 0,]


# Add month/year intervals for grouping
case_age$age_buckets <- findInterval(case_age$age_of_case_days, 
c(30L,90L,180L,365L, 730L, 1095L, 1460L, 1825L, 2190L, 2555L, 2920L, 3285L, 3650L,Inf),rightmost.closed = TRUE)

age_intervals <- data.frame('age_buckets'=seq(0,13),'age_interval'=c('less than one month','one to three months','three to six months','six months to one year',"one to two years", "two to three years", "three to four years", "four to five years", "five to six years", "six to seven years", "seven to eight years", "eight to nine years", "nine to ten years","more than 10 years"))
case_age <- left_join(case_age, age_intervals, by=NULL)
```

```{r case-age-dataset}
case_age_dataset <- case_age %>% group_by(state_name, district_name, court_name, est_code, updated_type_name, updated_disp_name, disp_nature, fil_year, reg_year_date, decision_year, age_interval) %>% summarise(total_cases = length(cino))
```


## Cases pending trial at the end of each year
```{r}
case_age$pending_trial_year_flag <- 0
case_age$pending_trial_year_flag[case_age$age_of_case_days >= 365] <- 1

pending_trial_dataset <- case_age %>% filter(pending_trial_year_flag == 1) %>% group_by(state_name, district_name, reg_year_date, fil_year, court_name, est_code, updated_type_name, updated_disp_name, disp_nature) %>% summarise(cases_pending_trial_yearly = length(cino))

total_yearly_cases <- case_age %>% group_by(state_name, district_name, reg_year_date, fil_year, court_name, est_code, updated_type_name, updated_disp_name, disp_nature) %>% summarise(total_cases = length(cino))

yearly_cases_pendency_ratio <- left_join(total_yearly_cases, pending_trial_dataset, by=NULL)
yearly_cases_pendency_ratio$cases_pending_trial_yearly[is.na(yearly_cases_pendency_ratio$cases_pending_trial_yearly)] <- 0
```

<!-- Cases where the year of registration is < 2019 and are pending, but are still not categorised under cases pending trial yearly. -->

<!-- This is happening because we are calculating the number of days between date of registration and **March 31, 2020**. Filing dates for such cases are mentioned in 2019 which is different from the year of filing (< 2019) -->

<!-- ```{sql connection=con, output.var='cases_from_2016_karbi_anglong'} -->
<!-- select *  from case_details where fil_year = '2016' AND district_name='Karbi Anglong' AND date_of_filing = '2019-05-06' -->
<!-- ``` -->


```{sql connection=con, output.var='case_type_patterns'}
select state_name, district_name, updated_type_name, count(cino) as total_cases from case_details  where case_flag = '1' group by state_name, district_name, updated_type_name
```

```{sql connection=con, output.var='case_disposal_patterns_overall'}
select updated_disp_name, disp_nature, count(cino) as total_cases from case_details where case_flag = '1' group by updated_disp_name, disp_nature
```

```{sql connection=con, output.var='case_disposal_patterns_by_district'}
select updated_disp_name, disp_nature, state_name, district_name, count(cino) as total_cases from case_details where case_flag = '1' group by updated_disp_name, disp_nature, state_name, district_name
```


```{r Check total cases in each file}
f_year_wise_cases <- sum(year_wise_cases$total_cases)
f_year_wise_cases_pending <- sum(year_wise_cases$pending_cases)
f_year_wise_cases_disposed <- sum(year_wise_cases$disposed_cases)
f_nature_of_disposal <- sum(nature_of_disposal$total_cases)
f_case_age <- sum(case_age_dataset$total_cases)
f_cases_removed <- nrow(cases_removed)
f_pending_trial <- sum(yearly_cases_pendency_ratio$total_cases)

number_of_cases_df <- data.frame('file_name'=c('year_wise_cases','year_wise_cases_pending','year_wise_disposed','nature_of_disposal', 'case_age','cases_pending_trial_yearly','cases_removed_case_age'), number_of_cases = c(f_year_wise_cases, f_year_wise_cases_pending, f_year_wise_cases_disposed, f_nature_of_disposal, f_case_age,f_pending_trial,f_cases_removed))
```

```{r state-wise-case-list}
state_list <- dbxSelect(con, "select distinct state_name from case_details where case_flag = '1'") %>% unlist(use.names = FALSE)

fetch_state_cases <- function(state_name){
  state_cases <- dbxSelect(con, glue("select * from case_details where state_name = '{state_name}' AND case_flag = '1' "))
  print(glue("Total cases in {state_name} -> {nrow(state_cases)}"))
  write_csv(state_cases, glue("datasets/state_wise_cases/cases_{state_name}.csv"),append = FALSE)
  return(nrow(state_cases))
} 

lapply(state_list, fetch_state_cases)
```


```{r Writing Files}
write_csv(year_wise_cases,"datasets/year_wise_cases.csv")
write_csv(nature_of_disposal,"datasets/nature_of_disposal.csv")
# write_csv(nature_of_offence,"datasets/nature_of_offence.csv")
write_csv(case_age_dataset,"datasets/case_age_dataset.csv")
write_csv(yearly_cases_pendency_ratio,"datasets/yearly_cases_pendency_ratio.csv")
write_csv(case_type_patterns,"datasets/case_type_patterns.csv")
write_csv(case_disposal_patterns_overall,"datasets/case_disposal_patterns_overall.csv")
write_csv(case_disposal_patterns_by_district,"datasets/case_disposal_patterns_by_district.csv")

# On 02/06/20
write_csv(filing_year_0,"datasets/cases_filing_year_0.csv")
write_csv(filing_year_below_2012,"datasets/cases_filing_year_below_2012.csv")
write_csv(number_of_cases_df,"datasets/file_wise_total_cases.csv")

# On 03/06/20
write_csv(year_wise_FIR,"datasets/year_wise_FIR.csv")

# On 20/06/20
write_csv(master_case_file, "datasets/state_wise_cases/master_file_of_cases.csv")
```
