
# Setup {#setup}
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	eval=FALSE,
	message = FALSE,
	warning = FALSE
)
source("../scripts/source_files.R")
```

--- # To clean act and section details

```{r Get cino's with judgement for selected act_ids}
act_id <- 122

relevant_cases_sql <- glue("select cino from case_acts where act = '{act_id}'")
relevant_cases <- dbxSelect(conn = con, statement = relevant_cases_sql)
relevant_cinos <- noquote(paste0("'",relevant_cases$cino, "'",collapse = ','))
cino_with_judgement <- glue("select cino, judgment_link, judgment_path from case_details where cino IN ({relevant_cinos})")
cino_with_judgement_details <- dbxSelect(conn = con, statement = cino_with_judgement)
cases_with_judgement <- cino_with_judgement_details$cino[!is.na(cino_with_judgement_details$judgment_link)]
print(cases_with_judgement)
```

```{r issue with these acts}
acts_issue <- read_csv("datasets/to_standardise/acts_to_standardise.csv", col_types = cols(
  act_id = col_character(),
  act_name = col_character(),
  section_name = col_character(),
  act_name_std = col_character(),
  section_name_std = col_character(),
  act_issue_flag = col_character()
))
```

# Assign New ID's for combined acts

```{r assign new IDs}

get_combined_acts <- acts_issue[grepl(pattern = '&',x = acts_issue$act_name_std),]
updated_act_id_master <- data.frame()

# The POCSO act is not listed in these acts
get_combined_acts <- get_combined_acts[!get_combined_acts$act_id %in% c(1816,1946,2213,2936),]

for(i in 1:nrow(get_combined_acts)){
  all_acts <- strsplit(get_combined_acts$act_name_std[i],split = ' & ') %>% unlist() %>% stringr::str_trim()
  
  all_sections <- strsplit(get_combined_acts$section_name_std[i],split = ';') %>% unlist() %>% stringr::str_trim()
  
  new_act_df <-
    data.frame('act_name_std' = all_acts, 'section_name_std' = all_sections)  
  
  subsections_check <- grepl(new_act_df$section_name_std,pattern = '/')
  
  if(TRUE %in% subsections_check){
    rows_with_subsections <- new_act_df[subsections_check,]
    for(j in 1:nrow(rows_with_subsections)){
      act_name_sub <- rows_with_subsections$act_name_std[j]
      section_name_sub <- strsplit(rows_with_subsections$section_name_std[j],'/') %>% unlist()
      act_sub_df <- data.frame('act_name_std'=act_name_sub, 'section_name_std'=section_name_sub)
      new_act_df <- bind_rows(new_act_df, act_sub_df)
    }
  }
  
  new_act_df <- new_act_df[!grepl(new_act_df$section_name_std, pattern = '/'),]
  new_act_df$old_act_id <- get_combined_acts$act_id[i]
  new_act_df$new_act_id <- paste0(new_act_df$old_act_id,'_' ,seq(1:nrow(new_act_df)))
  
  updated_act_id_master <- bind_rows(updated_act_id_master, new_act_df)
}
names(updated_act_id_master)[which(names(updated_act_id_master) == 'new_act_id')] <- 'act_id'
updated_act_id_master$act_issue_flag <- '0'
```

```{r}
# Building the acts_codebook (Updating acts where act_name was a combination of two acts)
acts_codebook <- bind_rows(acts_issue, updated_act_id_master)
write_csv(acts_codebook, "datasets/codebook/acts_sections_codebook.csv")
```


```{r Update act IDs in cases with combined acts}
act_mapping_df <- acts_codebook[!is.na(acts_codebook$old_act_id), c('old_act_id', 'act_id')] %>% unique() %>% data.frame()

old_act_ids <- act_mapping_df$old_act_id %>% unique()

old_act_ids_list <- noquote(paste0("'",old_act_ids,"'",collapse = ','))

get_case_details <- glue("select * from case_acts where act IN ({old_act_ids_list})")
case_act_update <- dbxSelect(conn = con, statement = get_case_details)
case_act_update$act <- as.character(case_act_update$act)
case_act_update <- left_join(case_act_update, act_mapping_df, by=c('act'='old_act_id'))
case_act_update$act <- NULL
names(case_act_update)[which(names(case_act_update) == 'act_id')] <- 'act'
```


```{sql connection=con}
ALTER TABLE case_acts DROP CONSTRAINT case_acts_act_fkey;
```
```{sql connection=con}
ALTER TABLE act ALTER COLUMN id TYPE varchar
```
```{sql connection=con}
ALTER TABLE case_acts ALTER COLUMN act TYPE varchar
```

```{r}
dbxInsert(con, 'case_acts',  case_act_update)
```

```{r}
insert_acts <- acts_codebook[!is.na(acts_codebook$old_act_id), c('act_id','act_name_std','section_name_std')] %>% unique()
names(insert_acts) <- c('id', 'name', 'section')
```

```{r}
dbxInsert(con, 'act',  insert_acts)
```

```{sql connection=con}
ALTER TABLE case_acts ADD CONSTRAINT case_acts_act_fkey FOREIGN KEY (act) REFERENCES act(id)
```

--- Start here to create a case level dataset for acts

```{r}
acts_codebook <- read_csv("datasets/codebook/acts_sections_codebook.csv", 
    col_types = cols(act_id = col_character(), 
        act_issue_flag = col_character(), 
        old_act_id = col_character()))
```

```{sql connection=con, output.var='valid_cases_with_act_id'}
select a.* from case_acts as a left join case_details as b on a.cino=b.cino where b.case_flag = '1' 
```

Get act details from the act/section codebook

```{r}
valid_cases_with_act_details <- left_join(valid_cases_with_act_id, acts_codebook, by=c('act'='act_id'))
valid_cases_with_act_details <- valid_cases_with_act_details[valid_cases_with_act_details$act_issue_flag == 0,]
valid_cases_with_act_details <- valid_cases_with_act_details[!is.na(valid_cases_with_act_details$cino),]
```

Prepare an empty df with cino + all act columns

```{r}
act_cols <- unique(acts_codebook$act_name_std[acts_codebook$act_issue_flag == 0])
all_acts <- c('cino',act_cols) %>% data.frame(row.names = NULL, check.names = FALSE) %>% t() %>% data.frame(row.names = NULL, check.names = FALSE)
names(all_acts)[] <- all_acts[1,]
all_acts <- all_acts[-1,] 
```

Fetch comma separated act info for all cases in the empty df

```{r prepare case_act dataframe, message=FALSE, warning=FALSE, include=FALSE}
unique_case_numbers <- unique(valid_cases_with_act_id$cino)
master_case_df <- data.frame(matrix(nrow = 0, ncol = (length(act_cols)+2), data = ''))
names(master_case_df) <- c(act_cols, 'act_issue_flag', 'cino')
loop_start <- print(glue("Lopp start time - {timestamp()}"))
for(i in 1:length(unique_case_numbers)){
  
  print(glue("Case Number: {i}"))
  act_issue_flag <- 0
  all_sections <- c()
  case_details <- unique_case_numbers[i]
  for(j in 1:length(act_cols)){
    
    act_details <- act_cols[j]
    all_act_sections <- valid_cases_with_act_details$section_name_std[valid_cases_with_act_details$cino == case_details & valid_cases_with_act_details$act_name_std == act_details]
    
    if(length(all_act_sections)>0){
    section_details <- paste0(all_act_sections, collapse = " ; ")
    act_issue_flag <- act_issue_flag +  sum(as.numeric(valid_cases_with_act_details$act_issue_flag[valid_cases_with_act_details$cino == case_details & valid_cases_with_act_details$act_name_std == act_details]))
    } else {
      section_details <- ''
    }
    all_sections <- c(all_sections, section_details)
  }
  
  
  section_details_df <- all_sections %>% t() %>% data.frame(row.names = NULL)
  names(section_details_df)[] <- act_cols
  # If one of the act/section ID's is flagged then the case is marked with a flag of 1
  section_details_df$act_issue_flag <- as.character(ifelse(act_issue_flag > 0, 1, 0))
  section_details_df$cino <- case_details
  master_case_df <- bind_rows(master_case_df, section_details_df)

}
loop_end <- print(glue("Lopp end time - {timestamp()}"))
```

```{sql connection=con, output.var='case_details_file'}
select cino, state_name, district_name from case_details where case_flag = '1'
```

```{r}
case_act_master <- left_join(case_details_file, master_case_df, by='cino')

write_csv(case_act_master, "datasets/cases_with_acts.csv")
```


