# Case Patterns

## Case Disposal Patterns - Case Age dataset

case_disposal_patterns_case_age <- c("Disposed of",
"TRANSFER",
"Disposed off on contest",
"Rejected",
"Disposed off",
"Judgement",
"Stay",
"TRANSFERED",
"CONCILLIATION",
"Disposed",
"Amalgated",
"Sent to Addl. Dist. and Sessions Judge Court, Bajali for Disposal",
"Convert",
"Transfer to District and Sessions Judge, Baksa for Disposal",
"Judgment delivered",
"Disposed off.",
"Dormant Case.",
"OTHERWISE",
"Stayed",
"TRANSFERED TO LOWER COURT.",
"Converted",
"Conviction followed by Acquittal.",
"Transfered to CJM Establishment.",
"Converted to TS(L/A)",
"Plaintiff suit is dissmissed Counter claims decreed",
"Judgment",
"ADR",
"Absolute",
"Case record do not belong to this court",
"Transferred to CJM Court Complex, Guwahati",
"Transfer to District and Sessions Judge",
"Disposed on Uncontest",
"Transfer to Outside Complex",
"Transferred to Baksa District Court",
"disposed of on full satisfaction",
"Transfer outside the complex",
"Converted to",
"Transfer to BNC",
"COMPROMISE",
"Proceeding is droped",
"QUASHED",
"COMPROMISED",
"P.O. CONSIGNED",
"PROBATION GRANTED",
"PROCEEDINGS STOPPED",
"ADJOURNED SINEDIE",
"DECREED",
"CONTESTED",
"DEFENDANT / RESPONDENT / ACCUSED DIED",
"PLEAD GUILTY",
"RESTORATION",
"DISMISSED AS COMPROMISED",
"SINE-DIE",
"DISMISSED AS WITHDRAWN  AS SATISFIED",
"DEATH",
"SETTLED IN LOK ADALAT",
"SATISFIED",
"CONSIGNED AFTER PROCEEDING U/S 299 CR.P.C",
"Sine Die",
"TRANSFERRED",
"DISPOSED OF WITH DIRECTIONS",
"Confession",
"COMPOUNDED AND DISPOSED OF.",
"Attached with Main case",
"DISMISSED IN DEFAULT U/O 9 RULE 3 OF CPC",
"DISMISSED AS SATISFIED",
"FIR QUASHED",
"P O",
"Proclaimed Offenders",
"AWARD PASSED",
"Disposed of being fully satisfied",
"Consigned",
"Accepting",
"Disposed otherwise",
"Some Convicted and sentenced, Some Acquitted",
"Proclaimed Offender",
"Probation",
"DISMISSED AS WITHDRAWN BEING NOT SATISFIED",
"DECREED WITH COSTS",
"DISMISSED IN DEFAULT U/O 9 RULE 8 OF CPC",
"P.O ( Proclomation Ofunder)",
"ADR /SETTLED/COMPROMISE/COMPOUNDED AND DISPOSED OF",
"DISMISSED U/O 17 RULE 3 OF CPC",
"Disposed of Otherwise remand paper attached with challan",
"DISPOSAL BEING FULLY SATISFIED",
"ACCEPTED",
"DISPOSE OFF/Consigned",
"Attached with main file",
"Proclaim offender",
"Dismised",
"SineDie",
"DECREED WITH NO COSTS",
"DISMISSED U/O 9 RULE 2 OF CPC",
"DISMISSED WITH NO COSTS",
"DISSMISED BEING INFRUCTUOUS",
"CONSENT DECREE",
"SENT BACK",
"DISMISSED AS NOT SATISFIED")


## Case Disposal Patterns - Nature of disposal dataset (Rate of conviction and acquittal)

case_disposal_patterns_nature_of_disposal <- c("CANCEL", "CLUBBED IN FIR", "SET ASIDE", "QUASH", "P.O. CONSIGN", "PARTLY DECREED WITH COSTS", "Proceeding close", "PROCEEDING STOP")
 
